api_platform:
    title: 'Youplan API'
    description: 'Youplan API for eponyme PWA'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
